# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 561aed1e3f56833ff2298cd84f3e1500a61868ee313314b04c84f4f3166643f0a0c5a5549b6b7513f17947a1d74cbd2c4077bef5ca897f517474587eeb04f857

test:
  secret_key_base: 6bfdc2b55cb71d863d8b5196df139c00e37e3b08dfe72e0ff3c21d4c2696709798d1ccbf8dbe6da114f425fb4045cb4e8dffe4975385e0b9b819e7c543e6907f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
